In [5]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
import csv

In [8]:
confirmed = pd.read_csv("Resources/time_series_covid_19_confirmed_US.csv")

In [9]:
deaths = pd.read_csv("Resources/time_series_covid_19_deaths_US.csv")

In [10]:
covidtotal = confirmed.merge(deaths, on="UID")
covidtotal.head()

,UID,iso2_x,iso3_x,code3_x,FIPS_x,Admin2_x,Province_State_x,Country_Region_x,Lat_x,Long__x,...,1/12/21_y,1/6/21-1/12/21_y,1/13/21_y,1/14/21_y,1/15/21_y,1/16/21_y,1/17/21_y,1/18/21_y,1/19/21_y,1/13/21-1/19/21_y
0,84001001,US,USA,840,1001.0,Autauga,Alabama,US,32.539527,-86.644082,...,55,367,55,55,55,55,55,55,55,385
1,84001003,US,USA,840,1003.0,Baldwin,Alabama,US,30.727750,-87.722071,...,175,1207,175,177,179,182,182,182,183,1260
2,84001005,US,USA,840,1005.0,Barbour,Alabama,US,31.868263,-85.387129,...,35,245,35,36,36,36,36,36,36,251
3,84001007,US,USA,840,1007.0,Bibb,Alabama,US,32.996421,-87.125115,...,48,336,48,47,47,47,47,47,47,330
4,84001009,US,USA,840,1009.0,Blount,Alabama,US,33.982109,-86.567906,...,79,524,80,80,83,83,83,83,83,575

In [21]:
IUD = []
city = []
state = []
country = []
lat = []
long = []
jan_22_april_22_confirmed = []
jan_22_april_22_deaths = []



IUD = covidtotal["UID"].to_list()
city = covidtotal["Admin2_x"].to_list()
state = covidtotal["Province_State_x"].to_list()
country = covidtotal["Country_Region_x"].to_list()
lat = covidtotal["Lat_x"].to_list()
long = covidtotal["Long__x"].to_list()
jan22_apr22_confirmed = covidtotal["1/22/20-4/22/20_x"].to_list()
jan22_apr22_deaths = covidtotal["1/22/20-4/22/20_y"].to_list()
apr23_confirmed = covidtotal["4/23/20-4/29/20_x"].to_list()
apr23_deaths = covidtotal["4/23/20-4/29/20_y"].to_list()
apr30_confirmed = covidtotal["4/30/20-5/6/20_x"].to_list()
apr30_deaths = covidtotal["4/30/20-5/6/20_y"].to_list()
may7_confirmed = covidtotal["5/7/20-5/13/20_x"].to_list()
may7_deaths = covidtotal["5/7/20-5/13/20_y"].to_list()
may14_confirmed = covidtotal["5/14/20-5/20/20_x"].to_list()
may14_deaths = covidtotal["5/14/20-5/20/20_y"].to_list()
may21_confirmed = covidtotal["5/21/20-5/27/20"].to_list()
may21_deaths = covidtotal["5/21/20-5/27/20_y"].to_list()
may28_confirmed = covidtotal["5/28/20-6/3/20_x"].to_list()
may28_deaths = covidtotal["5/28/20-6/3/20_y"].to_list()
jun4_confirmed = covidtotal["6/4/20-6/10/20_x"].to_list()
jun4_deaths = covidtotal["6/4/20-6/10/20_y"].to_list()
jun11_confirmed = covidtotal["6/11/20-6/17/20_x"].to_list()
jun11_deaths = covidtotal["6/11/20-6/17/20_y"].to_list()
jun18_confirmed = covidtotal["6/18/20-6/24/20_x"].to_list()
jun18_deaths = covidtotal["6/18/20-6/24/20_y"].to_list()
jun25_confirmed = covidtotal["6/25/20-7/1/20_x"].to_list()
jun25_deaths = covidtotal["6/25/20-7/1/20_y"].to_list()
jul2_confirmed = covidtotal["7/2/20-7/8/20_x"].to_list()
jul2_deaths = covidtotal["7/2/20-7/8/20_y"].to_list()
jul9_confirmed = covidtotal["7/9/20-7/15/20_x"].to_list()
jul9_deaths = covidtotal["7/9/20-7/15/20_y"].to_list()
jul16_confirmed = covidtotal["7/16/20-7/22/20_x"].to_list()
jul16_deaths = covidtotal["7/16/20-7/22/20_y"].to_list()
break1_confirmed = covidtotal["Break 1 7/23/20-8/18/20_x"].to_list()
break1_deaths = covidtotal["Break 1 7/23/20-8/18/20_y"].to_list()
aug19_confirmed = covidtotal["8/19/20-8/25/20_x"].to_list()
aug19_deaths = covidtotal["8/19/20-8/25/20_y"].to_list()
aug26_confirmed = covidtotal["8/26/20-9/1/20_x"].to_list()
aug26_deaths = covidtotal["8/26/20-9/1/20_y"].to_list()
sep2_confirmed = covidtotal["9/2/20-9/8/20_x"].to_list()
sep2_deaths = covidtotal["9/2/20-9/8/20_y"].to_list()
sep9_confirmed = covidtotal["9/9/20-9/15/20_x"].to_list()
sep9_deaths = covidtotal["9/9/20-9/15/20_y"].to_list()
sep16_confirmed = covidtotal["9/16/20-9/22/20_x"].to_list()
sep16_deaths = covidtotal["9/16/20-9/22/20_y"].to_list()
sep23_confirmed = covidtotal["9/23/20-9/29/20_x"].to_list()
sep23_deaths = covidtotal["9/23/20-9/29/20_y"].to_list()
sep30_confirmed = covidtotal["9/30/20-10/6/20_x"].to_list()
sep30_deaths = covidtotal["9/30/20-10/6/20_y"].to_list()
oct7_confirmed = covidtotal["10/7/20-10/13/20_x"].to_list()
oct7_deaths = covidtotal["10/7/20-10/13/20_y"].to_list()
oct14_confirmed = covidtotal["10/14/20-10/20/20_x"].to_list()
oct14_deaths = covidtotal["10/14/20-10/20/20_y"].to_list()
oct21_confirmed = covidtotal["10/21/20-10/27/20_x"].to_list()
oct21_deaths = covidtotal["10/21/20-10/27/20_y"].to_list()
oct28_confirmed = covidtotal["10/28/20-11/3/20_x"].to_list()
oct28_deaths = covidtotal["10/28/20-11/3/20_y"].to_list()
nov4_confirmed = covidtotal["11/4/20-11/10/20_x"].to_list()
nov4_deaths = covidtotal["11/4/20-11/10/20_y"].to_list()
nov11_confirmed = covidtotal["11/11/20-11/17/20_x"].to_list()
nov11_deaths = covidtotal["11/11/20-11/17/20_y"].to_list()
nov18_confirmed = covidtotal["11/18/20-11/24/20_x"].to_list()
nov18_deaths = covidtotal["11/18/20-11/24/20_y"].to_list()
nov25_confirmed = covidtotal["11/25/20-12/1/20_x"].to_list()
nov25_deaths = covidtotal["11/25/20-12/1/20_y"].to_list()
dec2_confirmed = covidtotal["12/2/20-12/8/20_x"].to_list()
dec2_deaths = covidtotal["12/2/20-12/8/20_y"].to_list()
dec9_confirmed = covidtotal["12/9/20-12/15/20_x"].to_list()
dec9_deaths = covidtotal["12/9/20-12/15/20_y"].to_list()
dec16_confirmed = covidtotal["12/16/20-12/22/20_x"].to_list()
dec16_deaths = covidtotal["12/16/20-12/22/20_y"].to_list()
break2_confirmed = covidtotal["Break 2 12/23/20-1/5/21_x"].to_list()
break2_deaths = covidtotal["Break 2 12/23/20-1/5/21_y"].to_list()
jan6_confirmed = covidtotal["1/6/21-1/12/21_x"].to_list()
jan6_deaths = covidtotal["1/6/21-1/12/21_y"].to_list()
jan13_confirmed = covidtotal["1/13/21-1/19/21_x"].to_list()
jan13_deaths = covidtotal["1/13/21-1/19/21_y"].to_list()

coviddata = {
    "IUD": IUD,
    "City": city, 
    "State": state,
    "Country": country, 
    "Latitude": lat,
    "Longitude": long,
    "Jan 22 - Apr 22 Cases": jan22_apr22_confirmed,
    "Jan 22 - Apr 22 Deaths": jan22_apr22_deaths,
    "Apr 23 - Apr 29 Cases": apr23_confirmed,
    "Apr 23 - Apr 29 Deaths": apr23_deaths,
    "Apr 30 - May 6 Cases": apr30_confirmed,
    "Apr 30 - May 6 Deaths": apr30_deaths,
    "May 7 - May 13 Cases": may7_confirmed,
    "May 7 - May 13 Deaths": may7_deaths,
    "May 14 - May 20 Cases": may14_confirmed,
    "May 14 - May 20 Deaths": may14_deaths,
    "May 21 - May 27 Cases": may21_confirmed,
    "May 21 - May 27 Deaths": may21_deaths,
    "May 28 - Jun 3 Cases": may28_confirmed,
    "May 28 - Jun 3 Deaths": may28_deaths,
    "Jun 4 - Jun 10 Cases": jun4_confirmed,
    "Jun 4 - Jun 10 Deaths": jun4_deaths,
    "Jun 11 - Jun 17 Cases": jun11_confirmed,
    "Jun 11 - Jun 17 Deaths": jun11_deaths,
    "Jun 18 - Jun 24 Cases": jun18_confirmed,
    "Jun 18 - Jun 24 Deaths": jun18_deaths,
    "Jun 25 - Jul 1 Cases": jun25_confirmed,
    "Jun 25 - Jul 1 Deaths": jun25_deaths,
    "Jul 2 - Jul 8 Cases": jul2_confirmed,
    "Jul 2 - Jul 8 Deaths": jul2_deaths,
    "Jul 9 - Jul 15 Cases": jul9_confirmed,
    "Jul 9 - Jul 15 Deaths": jul9_deaths,
    "Jul 16 - Jul 21 Cases": jul16_confirmed,
    "Jul 16 - Jul 21 Deaths": jul16_deaths,
    "Break 1 Jul 22 - Aug 18 Cases": break1_confirmed,
    "Break 1 Jul 22 - Aug 18 Deaths": break1_deaths,
    "Aug 19 - Aug 25 Cases": aug19_confirmed,
    "Aug 19 - Aug 25 Deaths": aug19_deaths,
    "Aug 26 - Sep 1 Cases": aug26_confirmed,
    "Aug 26 - Sep 1 Deaths": aug26_deaths,
    "Sep 2 - Sep 8 Cases": sep2_confirmed,
    "Sep 2 - Sep 8 Deaths": sep2_deaths,
    "Sep 9 - Sep 15 Cases": sep9_confirmed,
    "Sep 9 - Sep 15 Deaths": sep9_deaths,
    "Sep 16 - Sep 22 Cases": sep16_confirmed,
    "Sep 16 - Sep 22 Deaths": sep16_deaths,
    "Sep 23 - Sep 29 Cases": sep23_confirmed,
    "Sep 23 - Sep 29 Deaths": sep23_deaths,
    "Sep 30 - Oct 6 Cases": sep30_confirmed,
    "Sep 30 - Oct 6 Deaths": sep30_deaths,
    "Oct 7 - Oct 13 Cases": oct7_confirmed,
    "Oct 7 - Oct 13 Deaths": oct7_deaths,
    "Oct 14 - Oct 20 Cases": oct14_confirmed,
    "Oct 14 - Oct 20 Deaths": oct14_deaths,
    "Oct 20 - Oct 27 Cases": oct21_confirmed,
    "Oct 20 - Oct 27 Deaths": oct21_deaths,
    "Oct 28 - Nov 3 Cases": oct28_confirmed,
    "Oct 28 - Nov 3 Deaths": oct28_deaths,
    "Nov 4 - Nov 10 Cases": nov4_confirmed,
    "Nov 4 - Nov 10 Deaths": nov4_deaths,
    "Nov 11 - Nov 17 Cases": nov11_confirmed,
    "Nov 11 - Nov 17 Deaths": nov11_deaths,
    "Nov 17 - Nov 24 Cases": nov18_confirmed,
    "Nov 17 - Nov 24 Deaths": nov18_deaths,
    "Nov 25 - Dec 1 Cases": nov25_confirmed,
    "Nov 25 - Dec 1 Deaths": nov25_deaths,
    "Dec 2 - Dec 8 Cases": dec2_confirmed,
    "Dec 2 - Dec 8 Deaths": dec2_deaths,
    "Dec 9 - Dec 15 Cases": dec9_confirmed,
    "Dec 9 - Dec 15 Deaths": dec9_deaths,
    "Dec 16 - Dec 22 Cases": dec16_confirmed,
    "Dec 16 - Dec 22 Deaths": dec16_deaths,
    "Break 2 Dec 23 - Jan 5 Cases": break2_confirmed,
    "Break 2 Dec 23 - Jan 5  Deaths": break2_deaths,
    "Jan 6 - Jan 12 Cases": jan6_confirmed,
    "Jan 6 - Jan 12 Deaths": jan6_deaths,
    "Jan 13 - Jan 19 Cases": jan13_confirmed,
    "Jan 13 - Jan 19 Deaths": jan13_deaths
}

covid_df = pd.DataFrame(coviddata)
covid_df.head()

,IUD,City,State,Country,Latitude,Longitude,"Jan 22-April 22, 2020 Cases","Jan 22-April 22, 2020 Deaths"
0,84001001,Autauga,Alabama,US,32.539527,-86.644082,468,20
1,84001003,Baldwin,Alabama,US,30.727750,-87.722071,1784,37
2,84001005,Barbour,Alabama,US,31.868263,-85.387129,237,0
3,84001007,Bibb,Alabama,US,32.996421,-87.125115,353,0
4,84001009,Blount,Alabama,US,33.982109,-86.567906,435,0